### ISSUE TITLE
Download URL Not Working

### ISSUE THREAD

**Issue by empmdk** [Forgotten-Games-net/call-of-duty-classic-docker#1]
Can you re-upload the file somewhere?

**Comment by lstolcman** [comment]
@KeinNerd could you post a new link?

**Comment by fistwho** [comment]
@empmdk @lstolcman i fixed the dl and re-upload it. Sorry for the long waiting. 
Attention, the Container Image Name is different. The new is "forgottengames/call-of-duty-classic-docker"
